### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by muratdemirtas** [EmcraftSystems/linux-emcraft#14]
Hello Friend,

I'm trying to build stock kernel from your linux-k70 bsp. When i entered /projects/networking directory and execute make iam getting this error output

`make[1]: Leaving directory '/home/murat/Desktop/linux/A2F/busybox'
cp -f networking.initramfs /home/murat/Desktop/linux/linux/initramfs-list-min
rm -f /home/murat/Desktop/linux/linux/usr/initramfs_data.cpio \
	/home/murat/Desktop/linux/linux/usr/initramfs_data.cpio.gz
cp -f networking.kernel.K70 /home/murat/Desktop/linux/linux/.config
cp -f /home/murat/Desktop/linux/linux/arch/arm/kernel/vmlinux.lds.S.good \
	/home/murat/Desktop/linux/linux/arch/arm/kernel/vmlinux.lds.S
([ -e networking.lds.K70 ] && \
	cp -f networking.lds.K70 \
	/home/murat/Desktop/linux/linux/arch/arm/kernel/vmlinux.lds.S) || \
true;
make -C /home/murat/Desktop/linux/linux uImage SAMPLE=networking
make[1]: Entering directory '/home/murat/Desktop/linux/linux'
scripts/kconfig/conf -s arch/arm/Kconfig
  CHK     include/linux/version.h
  CHK     include/generated/utsrelease.h
make[2]: 'include/generated/mach-types.h' is up to date.
  CALL    scripts/checksyscalls.sh
<stdin>:46: warning: "__IGNORE_migrate_pages" redefined
/home/murat/Desktop/linux/linux/arch/arm/include/asm/unistd.h:474: note: this is the location of the previous definition
  CHK     include/generated/compile.h
  GEN     usr/initramfs_data.cpio
  AS      usr/initramfs_data.o
  LD      usr/built-in.o
  LDS     arch/arm/kernel/vmlinux.lds
  TIMEC   kernel/timeconst.h
Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at kernel/timeconst.pl line 373.
/home/murat/Desktop/linux/linux/kernel/Makefile:133: recipe for target 'kernel/timeconst.h' failed
make[2]: *** [kernel/timeconst.h] Error 255
Makefile:884: recipe for target 'kernel' failed
make[1]: *** [kernel] Error 2
make[1]: Leaving directory '/home/murat/Desktop/linux/linux'
../Rules.make:90: recipe for target 'networking.uImage' failed
make: *** [networking.uImage] Error 2
`

bc package at latest version, how do i fix this error ? thanks a lot of.

**Comment by muratdemirtas** [comment]
i solved this issue with changed my operating system to ubuntu 12.04 from 16.04.

**Comment by sposelenov** [comment]
Hello,


On 25.09.2017 5:41, Murat Demirtaş wrote:
>
> i solved this issue with changed my operating system to ubuntu 12.04 
> from 16.04.
>
Sounds good. For older distributions, try to apply this fix to Emcraft 
kernel.

Regards,
Sergei Poselenov,
Emcraft Systems
